"""Generate reviewable Cisco IOS-style configuration from allocated subnets."""

from __future__ import annotations

import re
from typing import Any


def _safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "_", value).strip("_-")
    return cleaned or "SUBNET"


def generate_cisco_ios_config(allocation: dict[str, Any]) -> str:
    """Render interface and DHCP-pool snippets; review before production use."""
    lines = [
        "! Generated by Automatic IPv4 Subnet Calculator and Network Designer",
        "! Review interface names, gateway policy, and exclusions before deployment.",
        "",
    ]
    used_vlan_ids = {
        int(subnet["vlan_id"])
        for subnet in allocation["subnets"]
        if subnet.get("vlan_id") is not None
    }
    next_vlan_id = 1
    used_labels: set[str] = set()
    for index, subnet in enumerate(allocation["subnets"], start=1):
        vlan_id = subnet.get("vlan_id")
        if vlan_id is None:
            while next_vlan_id in used_vlan_ids:
                next_vlan_id += 1
            vlan_id = next_vlan_id
            used_vlan_ids.add(next_vlan_id)
            next_vlan_id += 1
        label = _safe_name(str(subnet["name"]))
        base_label = label
        suffix = 1
        while label.casefold() in used_labels:
            suffix += 1
            label = f"{base_label}_{suffix}"
        used_labels.add(label.casefold())
        gateway = subnet["first_host"]
        network_address = subnet["network_address"]
        mask = subnet["subnet_mask"]

        lines.extend(
            [
                f"interface GigabitEthernet0/0.{vlan_id}",
                f" description {label}",
                f" encapsulation dot1Q {vlan_id}",
                f" ip address {gateway} {mask}",
                " no shutdown",
                "!",
                f"ip dhcp excluded-address {gateway}",
                f"ip dhcp pool {label}",
                f" network {network_address} {mask}",
                f" default-router {gateway}",
                "!",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"